Add step-ant
kaspar-p/types-of-ants pull request #8
Opened 2022-04-22 19:57 UTC by eamonma

Add step-ant

2022-04-22 19:58 UTC, taizhng commented
Love this open-source contribution, would however recommend changing the location of "step-ant".

Feel like it's slightly out of place.

2022-04-22 20:00 UTC, kaspar-p requested changes
I agree with @taizhng. The location of `aunt` has comedic effect. Maybe move it more towards the colors to break up some monotony?

2026-07-13 07:15 UTC, eamonma commented
@kaspar-p any plans to address this?

2026-07-13 12:42 UTC, kaspar-p commented
Sorry as per our contributing guidelines in [CONTRIBUTING](https://github.com/kaspar-p/types-of-ants/blob/main/CONTRIBUTING) we cannot accept this.

2026-07-13 12:42 UTC, closed without merging